snowflake_dbt:
  outputs:
    dev:
      account: [ACCOUNT]
      database: [DATABASE]
      password: [PASSWORD]
      role: [ROLE]
      schema: [SCHEMA]
      threads: 1
      type: snowflake
      user: [USER]
      warehouse: [WAREHOUSE]
  target: dev
