{{
    config(
        materialized='incremental',
        unique_id=['INVOICE_ID'],
        tags=['bronze'],
    )
}}

SELECT
    CAST(INVOICE_ID AS BIGINT) 						AS INVOICE_ID,
	CAST(PARENT_INVOICE_ID AS BIGINT) 				AS PARENT_INVOICE_ID,
	CAST(TRANSACTION_ID AS BIGINT) 					AS TRANSACTION_ID,
	CAST(ORGANIZATION_ID AS BIGINT) 				AS ORGANIZATION_ID,
	CAST(TYPE AS BIGINT) 							AS TYPE,
	STATUS,
	CURRENCY,
	PAYMENT_CURRENCY,
	PAYMENT_METHOD,
	CAST(AMOUNT AS NUMBER) 							AS AMOUNT,
	CAST(PAYMENT_AMOUNT AS NUMBER) 					AS PAYMENT_AMOUNT,
	CAST(FX_RATE AS FLOAT) 							AS FX_RATE, 
	CAST(FX_RATE_PAYMENT AS FLOAT) 					AS FX_RATE_PAYMENT,
	CAST(CREATED_AT AS TIMESTAMP) 					AS CREATED_AT,
	CAST(CREATED_AT AS DATE) 						AS DATE_ID,
	CAST(AMOUNT AS NUMBER)*CAST(FX_RATE AS FLOAT) 	AS VALUE_USD,
    CURRENT_TIMESTAMP() 							AS _incremental_sequence
FROM 
    {{source('RAW_PROD','INVOICES')}}

{% if is_incremental() %}
    WHERE _incremental_sequence > CURRENT_TIMESTAMP()
{% endif %}